# This rule is not used by the project placement-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over placement.openstack.org.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: placement-operator
    app.kubernetes.io/managed-by: kustomize
  name: placementapi-admin-role
rules:
- apiGroups:
  - placement.openstack.org
  resources:
  - placementapis
  verbs:
  - '*'
- apiGroups:
  - placement.openstack.org
  resources:
  - placementapis/status
  verbs:
  - get
